# Config file for go-test-coverage github action.
# go-actor-commence commits to keep 100% test coverage.

profile: cover.out
local-refix: "github.com/vladopajic/go-actor-commence"
threshold:
  total: 100
